require:
  - rubocop-rails

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

AsciiComments:
  Enabled: false