default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root      
  password: 
  host: localhost

development:
  <<: *default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: vb_development
  pool: 5
  username: root
  password:
  host: localhost

test:
  <<: *default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: vb_test
  pool: 5
  username: root
  password:
  host: localhost

production: 
  <<: *default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: vb_production
  pool: 5
  username: root
  password:
  host: localhost